# permissions for end users to view anotherreplicasets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: anotherreplicaset-viewer-role
rules:
- apiGroups:
  - replicaset.my.domain
  resources:
  - anotherreplicasets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - replicaset.my.domain
  resources:
  - anotherreplicasets/status
  verbs:
  - get
