# permissions for end users to edit anotherreplicasets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: anotherreplicaset-editor-role
rules:
- apiGroups:
  - replicaset.my.domain
  resources:
  - anotherreplicasets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - replicaset.my.domain
  resources:
  - anotherreplicasets/status
  verbs:
  - get
